language: node_js
node_js:
- '5'
- '6'
script:
- yarn install
- yarn run lint
- yarn test
- yarn run build
branches:
  only:
  - master
  - /^rc\/.*$/
cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.npm
deploy:
  skip_cleanup: true
  provider: npm
  email: djoeman84+npm@gmail.com
  on:
    branch: master
  api_key:
    secure: TVxZnZBibMSuaWR7q4/qNEduEgvgyCM2lldYV3B6Rfed1fpaNUFdbai1d3dxjA4iZKib1t3e+Wn67YNPPGCeBHyjXxbU7QcpvpaKptKomIqn/HW6QwKoDwFCAvFXe7IiefTqYhRHmKPuegtnL3fjJH37zWHcaozaZxbGlptEpe98G2D9AJkHTkcBxuqv4r4xcom/ghNE6eig1B7aks41SQGIby2aa7VcJoJZeJ4MXv/urbnVhzXZ1eGz7EpnpF0Bx1aP2KPISNeKIEGmQVvMJA61V1UzueMqe/EyOkSVmGlklGvlIbpeu0O1fsGJmkl8c/Uxp9Hm/G3lfmCBjHaaggfK5x6zcxEBP5Iu7HeENLA23/BHG6Ws1T62/ZkEg+l+KRLtf6JwKoSlpxjmepbVYg+IgBMPMOsjWdFxvivRV1Zb6nu2lpkdnBlCRWNO+TT9B/fU4DuNq6yu3oMB5+b0QUhCkNe78UK1wEeOO+CUChq128TXuAVXh6XpKjZlsl9yWQqo/nwNEQWN37Zu39Ou5xAP3VVwfAPQfIMyPS0xSzzGZ5obYXyXCNJs7nt/lToV5s9A0P7tMDyYnwN8OwMWdV/d5+n1i3PjpKIznp4Jj6napyCXgYCJhAs3CEKvVcnlOji5r18S5vD/LhKjZwkIKxF4/KRMtH/9myY5iWL4V5s=
